---
title: "cp1"
format: html
---

# Adv Data Viz CP

1. What geom do I use to create a barplot using the original raw data (not summarized)?
\
geom_bar
\
\
2. What geom do I use to create a barplot using already summarized data (from count())?
\
geom_col
\
\
7. Which of these geom lines of code provides a proportional bar chart?
\
\
ggplot(aes(x, fill) + geom_bar(position = 'fill')

# Adv Spatial Viz P1 CP

2. What are the two components of a CRS/GCS?
\
Datum + Ellipsoid Model
\
\
4. Why is it insufficient to identify a location by its latitude and longitude?
\
Longitude and latitude are calculated based on chosen a coordinate reference system (datum + ellipsoid model) and so that value of longitude and latitude of a location might change if the CRS changes.
\
\
5. Why do we need to be mindful about CRSs when working with different spatial datasets?
\
* Different CRSs may use different units (e.g., meters, feet). Consistency in units is essential for accurate distance and area calculations.
* Joining datasets from multiple sources requires a common CRS.
* Different datasets may use different CRSs. If these CRSs are not accounted for, the spatial points/regions will not align correctly on a map.
\
\

# Adv Data Wrangling P1 CP
1. sqrt(2)^2 == 2 is [1] FALSE
\
The computer first calculates sqrt(2) and saves some but not all decimal places of 1.414214... so when you square that number, it is almost but not quite 2.
\
\
2. TRUE & NA
\
[1] NA
\
\
3. TRUE | NA 
\
[1] TRUE
\
\
4. sum(c(TRUE,TRUE,FALSE,TRUE))
\
3
\
\
5. if_else(condition,true,false)
\
Useful when you are transforming values of a vector if a particular condition holds.
\
\
6. parse_number()
\
Useful when you have a variable that has non-numeric symbols such as $, %, or commas that you want to remove and convert to an integer or double numeric vector.
\
\
7. Recycling in R refers to
\
the repeating of a short vector when arithmetic (and logical operations) is used on two vectors of different lengths.
\
\
8. round(530.3,-2)
\
(530.3 %/% 100) * 100
\
\
9. fct_relevel()
\
Moving a small number of levels to the beginning of the ordering or manually reordering levels.
\
\
10. fct_recode()
\
Transforming the values/levels of a factor variable to new labels
\
\
11. fct_reorder()
\
Reordering the values/levels of a factor variable to by a different numeric/quantitative variable
\
\
12. fct_infreq()
\
Reordering the values/levels of a factor variable to by the frequency of the levels
\
\
13. What is ISO8601?
\
International standard for writing date-time, largest unit of time to smallest unit, yyyy-mm-dd hh:mm.
\
\
14. To work with dates and times in R, we should:
\
Convert character vectors such as "2024-07-23 1:35pm" to a date-time class (data type). 
\
\

# Adv Data Wrangling P2 CP
3. The correct way to recreate paste0("Letter of the Day: ",letters) with str_c() is
\
str_c("Letter of the Day: ",letters, sep = '')
\
\
4. "a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z"
\
str_c(letters, collapse = ', ')
\
str_flatten(letters,', ')
\
\
5. To separate a vector of strings (deliminted by commas) into columns of strings, use 
\
separate_wider_delim()
\
\
6. For the following string,

x1 <- "text\nEl Ni\xf1o was particularly bad this year"

one of these functions will give you meaningful data and one will not. Why? 

read_csv(x1)$text

read_csv(x1, locale = locale(encoding = "Latin1"))$text
\
Non-English (non-ASCII) characters can be encoded in a wide variety of ways and read_csv() uses UTF-8 encoding by default.
\
\
7. Which of these characters means that a pattern is optional (matches 0 or 1 time)?
\
?
\
\
8. Which of these characters means that a pattern is repeats (at least once)?
\
+
\
\
9. To replace all forward slahes with backslashes in "a/b/c/d/e", use the following code:
\
str_replace_all("a/b/c/d/e",'/',"\\\\")
\
\
10. A primary key is
\
is a variable or set of variables that uniquely identifies each observation
\
\
11. A foreign key is
\
is a variable (or set of variables) that corresponds to a primary key in another table
\
\
12. A natural join is
\
a join that uses all variables that appear in both data frames as the join key
\
\
13. Some examples of a non-equi join:
\
cross join and inequality join
\
\







